name: Deploy to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: 62.217.190.139
          username: dekunin
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/apps/cronos
            ./deploy.sh
      - name: Send Webhook Notification
        env:
          NOTIFICATION_WEBHOOK_URL: https://n8n.kunini.ru/webhook/489ce88c-f9e9-43ec-a36c-e5b787f6a287
          REPOSITORY: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
          COMMIT_SHA: ${{ github.sha }}
          ACTOR: ${{ github.actor }}
        run: |
          COMMIT_URL="https://github.com/$REPOSITORY/commit/$COMMIT_SHA"
          TEXT="🚀 *Deployment Successful!*

          ✅ Repository: *$REPOSITORY*
          🔄 Branch: *$BRANCH*
          🔧 Commit: [$COMMIT_SHA]($COMMIT_URL)
          💡 Triggered by: *$ACTOR*"
          PAYLOAD=$(TEXT="$TEXT" node -e 'process.stdout.write(JSON.stringify({ text: process.env.TEXT }))')

          curl --request POST \
            --url "$NOTIFICATION_WEBHOOK_URL" \
            --header 'content-type: application/json' \
            --data "$PAYLOAD"
